# First, add the API
apiVersion: apps/v1
# This will be the deployment setup
kind: Deployment
metadata:
  # Name your Deployment here
  name: number-to-text-dep
  labels:
    # label your deployment
    app: number-to-text-app
spec:
  # The number of pods/replicas to run
  replicas: 1            
  selector:
    matchLabels:
    # selector to match the pod
      app: number-to-text-app  
  template:
    metadata:
      labels:
      # label your pod
        app: number-to-text-app  
    spec:
      containers:
      # Add the container name for Kubernetes
      - name: number-to-text
      # Add the local image name
        image: number-to-text 
        # never pull the image policy
        imagePullPolicy: Never
        ports:
        # port for running the container
        - containerPort: 5001